server {
  listen ${PORT};
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  error_page 403 =200 /index.html;

  location / {
    try_files $uri $uri/index.html /index.html;
  }
}
